name: device-config-demo
version: "0.1"
summary: Ubuntu Device Configuration
description: |
  Device configuration for Ubuntu Core.
confinement: strict
grade: stable
base: core18

apps:
  run:
    command: bin/run
    daemon: simple
    plugs:
      - network
      - network-bind
      #- snapd-control          # it needs these privileged interfaces
      #- dbus                   #             --- " ---
      #- network-setup-control  #             --- " ---
      #- time-control           #             --- " ---
      #- timeserver-control     #             --- " ---
      #- timezone-control       #             --- " ---

parts:
  application:
    plugin: go
    go-importpath: github.com/CanonicalLtd/device-config
    source: .
    source-type: git
    build-packages:
      - gcc

  static:
    source: static
    plugin: dump
    organize:
      "*": /static/

  bin:
    source: snap/local
    plugin: dump
    organize:
      "*": /bin/

